https://vin-contact-service.herokuapp.com/api/contacts

###


GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: application/json

###

GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: application/xml

###


GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: application/json

### Re-S-T

GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: application/xml

###

GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: text/plain

###

POST /login HTTP/1.1
Host: vinbasket.herokuapp.com
Accept: application/json
Content-Type: application/xml

{"email":"vinod@vinod.co","password":"topsecret"}

###

GET /orders/5
Host: vinbasket.herokuapp.com
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZpbm9kIEt1bWFyIiwiaWF0IjoxNjY1Mzg0NDkzfQ.YJsgWVDynbKsoDI3OHMwTzvEGXc_H25xhCPf4dlFNOw
###

GET /api/quiz/user-marks
Host: vin-quizzer.herokuapp.com
Accept: application/json

###

GET /api/products
Host: localhost:8080
Accept: application/json

###

GET /api/products
Host: localhost:8080
Accept: application/xml

###

GET /api/products
Host: localhost:8080
Accept: text/csv

###


GET /api/products/678
Host: localhost:8080
Accept: application/json

###

POST /api/contacts
Host: vin-contact-service.herokuapp.com
Content-Type: application/json

{
  "firstname": "Vinod",
  "lastname": "Kumar",
  "gender": "Male",
  "email": "vinod@xmpl.com",
  "phone": "9731424784",
  "address": "9 Hermina Trail",
  "city": "Atlanta",
  "state": "Georgia",
  "country": "United States",
  "pincode": "31132",
  "picture": "https://vin-contact-service.herokuapp.com/images/men/1.jpeg"
}

###

GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: text/csv

###

GET /api/products/12 HTTP/1.1
Host: localhost:8080
Accept: application/json
###

GET /api/products/12 HTTP/1.1
Host: localhost:8080
Accept: application/xml
###

GET /api/products HTTP/1.1
Host: localhost:8080
Accept: text/csv

###

POST /api/products 
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
  "category": "vegetable",
  "name": "Chillies new",
  "brand": "KVinod",
  "description": "New Chillies big - Grade A",
  "quantity_per_unit": "100 GM",
  "unit_price": 15,
  "picture": "https://vinbasket.herokuapp.com/product-images/10000081_15-fresho-chilli-green-big-grade-a.jpg",
  "discount": 5
}

###
POST /api/products 
Host: localhost:8080
Content-Type: application/xml
Accept: application/xml

<?xml version="1.0" encoding="UTF-8" ?>
<product>
  <category>vegetable</category>
  <name>Newest Chillies</name>
  <brand>Modern</brand>
  <description>Newest Chillies big - Grade A</description>
  <quantity_per_unit>100 GM</quantity_per_unit>
  <unit_price>15</unit_price>
  <picture>https://vinbasket.herokuapp.com/product-images/10000081_15-fresho-chilli-green-big-grade-a.jpg</picture>
  <discount>4</discount>
</product>

###

PATCH /api/products/12
Host: localhost:8080
Content-Type: application/json
Accept: application/json

{
  "unit_price": 8,
  "discount": 14
}
###

PATCH /api/products/12
Host: localhost:8080
Content-Type: application/xml
Accept: application/xml

<?xml version="1.0" encoding="UTF-8" ?>
<product>
  <unit_price>9</unit_price>
  <discount>2</discount>
</product>