https://vin-contact-service.herokuapp.com/api/contacts

###


GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: application/json

###

GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: application/xml

###


GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: application/json

### Re-S-T

GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: application/xml

###

GET /api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Host: vin-contact-service.herokuapp.com
Accept: text/plain

###

POST /login HTTP/1.1
Host: vinbasket.herokuapp.com
Accept: application/json
Content-Type: application/xml

{"email":"vinod@vinod.co","password":"topsecret"}

###

GET /orders/5
Host: vinbasket.herokuapp.com
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZpbm9kIEt1bWFyIiwiaWF0IjoxNjY1Mzg0NDkzfQ.YJsgWVDynbKsoDI3OHMwTzvEGXc_H25xhCPf4dlFNOw
###

GET /api/quiz/user-marks
Host: vin-quizzer.herokuapp.com
Accept: application/json

###

GET /api/products
Host: localhost:8080
Accept: application/json

###

GET /api/products
Host: localhost:8080
Accept: application/xml

###

GET /api/products
Host: localhost:8080
Accept: text/csv

###


GET /api/products/678
Host: localhost:8080
Accept: application/json

###

POST /api/contacts
Host: vin-contact-service.herokuapp.com
Content-Type: application/json

{
  "firstname": "Vinod",
  "lastname": "Kumar",
  "gender": "Male",
  "email": "vinod@xmpl.com",
  "phone": "9731424784",
  "address": "9 Hermina Trail",
  "city": "Atlanta",
  "state": "Georgia",
  "country": "United States",
  "pincode": "31132",
  "picture": "https://vin-contact-service.herokuapp.com/images/men/1.jpeg"
}

###

GET /api/contacts
Host: vin-contact-service.herokuapp.com
Accept: text/csv

###

GET /api/products/122 HTTP/1.1
Host: localhost:8080
Accept: application/json
###

GET /api/products/122 HTTP/1.1
Host: localhost:8080
Accept: application/xml
